// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp3jhsK2fjkyzXczQ-mOTLFBdjH5u3XIw',
    appId: '1:472132576707:web:902da5bf169dd53e0d4976',
    messagingSenderId: '472132576707',
    projectId: 'rd-fresh',
    authDomain: 'rd-fresh.firebaseapp.com',
    storageBucket: 'rd-fresh.firebasestorage.app',
    measurementId: 'G-3BPL4CY5JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzpsIHsk1M8IbEeFrosJDjuRpWgurEGiE',
    appId: '1:472132576707:android:234b172a374db8c10d4976',
    messagingSenderId: '472132576707',
    projectId: 'rd-fresh',
    storageBucket: 'rd-fresh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxCESHHiP3YBFg3N7w2XtUZtcSA1VFzQ',
    appId: '1:472132576707:ios:19fe48ccb49be22b0d4976',
    messagingSenderId: '472132576707',
    projectId: 'rd-fresh',
    storageBucket: 'rd-fresh.firebasestorage.app',
    iosBundleId: 'com.example.rdfresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvxCESHHiP3YBFg3N7w2XtUZtcSA1VFzQ',
    appId: '1:472132576707:ios:19fe48ccb49be22b0d4976',
    messagingSenderId: '472132576707',
    projectId: 'rd-fresh',
    storageBucket: 'rd-fresh.firebasestorage.app',
    iosBundleId: 'com.example.rdfresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp3jhsK2fjkyzXczQ-mOTLFBdjH5u3XIw',
    appId: '1:472132576707:web:feaa62adbb3a95930d4976',
    messagingSenderId: '472132576707',
    projectId: 'rd-fresh',
    authDomain: 'rd-fresh.firebaseapp.com',
    storageBucket: 'rd-fresh.firebasestorage.app',
    measurementId: 'G-TZR7GHH5PD',
  );
}
